Bonobo.Git.Server/Bonobo.Git.Server/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.IO;
using System.Text;

namespace Bonobo.Git.Server.Controllers
{
    public class ImageController : Controller
    {
        public ActionResult Show(string repository, string tree, string path)
        {
            using (var browser = new RepositoryBrowser(Path.Combine(UserConfigurationManager.Repositories, repository)))
            {
                var leaf = browser.GetLeaf(tree, path);
                if (leaf != null)
                {
                    return new FileStreamResult(new MemoryStream(leaf.RawData), FileDisplayHandler.GetMimeType(Path.GetFileName(path)));
                }
            }
            return null;
        }
    }
}

Bonobo.Git.Server/Bonobo.Git.Server/Controllers/RepositoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Bonobo.Git.Server.Data;
using Bonobo.Git.Server.Security;
using Bonobo.Git.Server.Models;
using Bonobo.Git.Server.App_GlobalResources;
using System.IO;
using System.Configuration;
using System.Text.RegularExpressions;

namespace Bonobo.Git.Server.Controllers
{
    public class RepositoryController : Controller
    {
        [Dependency]
        public ITeamRepository TeamRepository { get; set; }

        [Dependency]
        public IRepositoryRepository RepositoryRepository { get; set; }

        [Dependency]
        public IMembershipService MembershipService { get; set; }

        [Dependency]
        public IRepositoryPermissionService RepositoryPermissionService { get; set; }

        [FormsAuthorizeAttribute]
        public ActionResult Index()
        {
            return View(GetIndexModel());
        }

        [FormsAuthorizeRepository(RequiresRepositoryAdministrator = true)]
        public ActionResult Edit(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var model = ConvertRepositoryModel(RepositoryRepository.GetRepository(id));
                PopulateEditData();
                return View(model);
            }
            return View();
        }

        [HttpPost]
        [FormsAuthorizeRepository(RequiresRepositoryAdministrator = true)]
        public ActionResult Edit(RepositoryDetailModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Administrators.Contains(User.Identity.Name))
                {
                    RepositoryRepository.Update(ConvertRepositoryDetailModel(model));
                    ViewBag.UpdateSuccess = true;
                }
                else
                {
                    ModelState.AddModelError("Administrators", Resources.Repository_Edit_CantRemoveYourself);
                }
            }
            PopulateEditData();
            return View(model);
        }

        [FormsAuthorizeAttribute]
        public ActionResult Create()
        {
            if (!User.IsInRole(Definitions.Roles.Administrator) && !UserConfigurationManager.AllowUserRepositoryCreation)
            {
                return RedirectToAction("Unauthorized", "Home");
            }

            var model = new RepositoryDetailModel
            {
                Administrators = new string[] { User.Identity.Name },
            };
            PopulateEditData();
            return View(model);
        }

        [HttpPost]
        [FormsAuthorizeAttribute]
        public ActionResult Create(RepositoryDetailModel model)
        {
            if (!User.IsInRole(Definitions.Roles.Administrator) && !UserConfigurationManager.AllowUserRepositoryCreation)
            {
                return RedirectToAction("Unauthorized", "Home");
            }

            if (model != null && !String.IsNullOrEmpty(model.Name))
            {
                model.Name = Regex.Replace(model.Name, @"\s", "");
            }

            if (String.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("Name", Resources.Repository_Create_NameFailure);
            }
            else if (ModelState.IsValid)
            {
                if (RepositoryRepository.Create(ConvertRepositoryDetailModel(model)))
                {
                    string path = Path.Combine(UserConfigurationManager.Repositories, model.Name);
                    if (!Directory.Exists(path))
                    {
                        using (var repository = new GitSharp.Core.Repository(new DirectoryInfo(path)))
                        {
                            repository.Create(true);
                        }
                        TempData["CreateSuccess"] = true;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        RepositoryRepository.Delete(model.Name);
                        ModelState.AddModelError("", Resources.Repository_Create_DirectoryExists);
                    }
                }
                else
                {
                    ModelState.AddModelError("", Resources.Repository_Create_Failure);
                }
            }
            PopulateEditData();
            return View(model);
        }

        [FormsAuthorizeRepository(RequiresRepositoryAdministrator = true)]
        public ActionResult Delete(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                return View(new RepositoryDetailModel { Name = id });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [FormsAuthorizeRepository(RequiresRepositoryAdministrator = true)]
        public ActionResult Delete(RepositoryDetailModel model)
        {
            if (model != null && !String.IsNullOrEmpty(model.Name))
            {
                string path = Path.Combine(UserConfigurationManager.Repositories, model.Name);
                if (Directory.Exists(path))
                {
                    DeleteFileSystemInfo(new DirectoryInfo(path));
                }
                RepositoryRepository.Delete(model.Name);
                TempData["DeleteSuccess"] = true;
            }
            return RedirectToAction("Index");
        }

        [FormsAuthorizeRepository]
        public ActionResult Detail(string id)
        {
            ViewBag.ID = id;
            if (!String.IsNullOrEmpty(id))
            {
                var model = ConvertRepositoryModel(RepositoryRepository.GetRepository(id));
                if (model != null)
                {
                    model.IsCurrentUserAdministrator = RepositoryPermissionService.IsRepositoryAdministrator(User.Identity.Name, id);
                }
                return View(model);
            }
            return View();
        }

        [FormsAuthorizeRepository]
        public ActionResult Tree(string id, string name, string path)
        {
            ViewBag.ID = id;
            if (!String.IsNullOrEmpty(id))
            {
                bool download = false;
                if (path != null)
                {
                    if (path.EndsWith(".browse"))
                    {
                        path = path.Substring(0, path.Length - 7);
                    }
                    else if (path.EndsWith(".download"))
                    {
                        path = path.Substring(0, path.Length - 9);
                        download = true;
                    }
                }
                path = path != null ? path.Replace(".browse", "") : null;
                using (var browser = new RepositoryBrowser(Path.Combine(UserConfigurationManager.Repositories, id)))
                {
                    string branchName;
                    var files = browser.Browse(name, path, out branchName);
                    PopulateBranchesData(browser, branchName);
                    PopulateAddressBarData(name, path);
                    return DisplayFiles(files, path, id, download);
                }
            }
            return View();
        }

        [FormsAuthorizeRepository]
        public ActionResult Commits(string id, string name)
        {
            ViewBag.ID = id;
            if (!String.IsNullOrEmpty(id))
            {
                using (var browser = new RepositoryBrowser(Path.Combine(UserConfigurationManager.Repositories, id)))
                {
                    string currentBranchName;
                    var commits = browser.GetCommits(name, out currentBranchName);
                    PopulateBranchesData(browser, currentBranchName);
                    return View(new RepositoryCommitsModel { Commits = commits, Name = id });
                }
            }

            return View();
        }

        [FormsAuthorizeRepository]
        public ActionResult Commit(string id, string commit)
        {
            ViewBag.ID = id;
            if (!String.IsNullOrEmpty(id))
            {
                using (var browser = new RepositoryBrowser(Path.Combine(UserConfigurationManager.Repositories, id)))
                {
                    var model = browser.GetCommitDetail(commit);
                    model.Name = id;
                    return View(model);
                }
            }

            return View();
        }

        private ActionResult DisplayFiles(IEnumerable<RepositoryTreeDetailModel> files, string path, string id, bool returnAsBinary)
        {
            if (files != null)
            {
                var model = new RepositoryTreeModel();
                model.Name = id;
                model.IsTree = !(files.Count() == 1 && !files.First().IsTree && files.First().Path == path);
                if (model.IsTree)
                {
                    model.Files = files.OrderByDescending(i => i.IsTree).ThenBy(i => i.Name);
                }
                else
                {
                    model.File = files.First();
                    if (!returnAsBinary)
                    {
                        model.Text = FileDisplayHandler.GetText(model.File.Data);
                        model.IsTextFile = model.Text != null;

                        if (model.IsTextFile)
                        {
                            model.TextBrush = FileDisplayHandler.GetBrush(model.File.Name);
                        }

                        if (!model.IsTextFile)
                        {
                            model.IsImage = FileDisplayHandler.IsImage(model.File.Name);
                        }
                    }

                    if (!model.IsImage && !model.IsTextFile)
                    {
                        using (var stream = new MemoryStream(model.File.Data))
                        {

Bonobo.Git.Server/Bonobo.Git.Server/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Bonobo.Git.Server.Data;
using Bonobo.Git.Server.Models;
using Bonobo.Git.Server.Security;
using Bonobo.Git.Server.App_GlobalResources;

namespace Bonobo.Git.Server.Controllers
{
    public class TeamController : Controller
    {
        [Dependency]
        public ITeamRepository TeamRepository { get; set; }

        [Dependency]
        public IMembershipService MembershipService { get; set; }

        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Index()
        {
            return View(ConvertTeamModels(TeamRepository.GetAllTeams()));
        }

        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Edit(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var model = ConvertTeamModel(TeamRepository.GetTeam(id));
                PopulateViewData();
                return View(model);
            }
            return View();
        }

        [HttpPost]
        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Edit(TeamDetailModel model)
        {           
            if (ModelState.IsValid)
            {
                TeamRepository.Update(ConvertTeamDetailModel(model));
                ViewBag.UpdateSuccess = true;
            }
            PopulateViewData();
            return View(model);
        }

        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Create()
        {
            var model = new TeamDetailModel { };
            PopulateViewData();
            return View(model);
        }

        [HttpPost]
        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Create(TeamDetailModel model)
        {
            while (!String.IsNullOrEmpty(model.Name) && model.Name.Last() == ' ')
            {
                model.Name = model.Name.Substring(0, model.Name.Length - 1);
            }

            if (ModelState.IsValid)
            {
                if (TeamRepository.Create(ConvertTeamDetailModel(model)))
                {
                    TempData["CreateSuccess"] = true;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", Resources.Team_Create_Failure);
                }
            }

            PopulateViewData();
            return View(model);
        }

        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Delete(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                return View(new TeamDetailModel { Name = id });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Delete(TeamDetailModel model)
        {
            if (model != null && !String.IsNullOrEmpty(model.Name))
            {
                TeamRepository.Delete(model.Name);
                TempData["DeleteSuccess"] = true;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [FormsAuthorizeAttribute]
        public ActionResult Detail(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                return View(ConvertTeamModel(TeamRepository.GetTeam(id)));
            }
            return View();
        }

        private IEnumerable<TeamDetailModel> ConvertTeamModels(IEnumerable<TeamModel> models)
        {
            var result = new List<TeamDetailModel>();
            foreach (var item in models)
            {
                result.Add(ConvertTeamModel(item));
            }
            return result;
        }

        private TeamDetailModel ConvertTeamModel(TeamModel model)
        {
            return model == null ? null : new TeamDetailModel
            {
                Name = model.Name,
                Description = model.Description,
                Members = model.Members,
                Repositories = model.Repositories,
            };
        }

        private TeamModel ConvertTeamDetailModel(TeamDetailModel model)
        {
            return new TeamModel
            {
                Name = model.Name,
                Description = model.Description,
                Members = model.Members,
                Repositories = model.Repositories,
            };
        }

        private void PopulateViewData()
        {
            ViewData["AvailableUsers"] = MembershipService.GetAllUsers().Select(i => i.Username).ToArray();
        }
    }
}

Bonobo.Git.Server/Bonobo.Git.Server/Views/Repository/Commit.cshtml
@model RepositoryCommitModel
@using Bonobo.Git.Server.Extensions
@{
    ViewBag.Title = Resources.Repository_Commit_Detail;
    Layout = "~/Views/Repository/_RepositoryLayout.cshtml";
}
@if (Model != null)
{
    <div class="uniForm">
        <fieldset class="inlineLabels detail">
            <h3>@Model.Name</h3>
        </fieldset>
    </div>
    <div class="repositoryContent">
        @Html.Partial("_Commit", Model)
        <div class="changes">
            <h3>@Model.GetType().GetDisplayValue("Changes")</h3>
            @foreach (var item in Model.Changes)
            {
                <div class="item">
                    <p>
                        @if (item.Type == GitSharp.ChangeType.Added)
                        {
                            <text><img src="@Url.Content("~/Content/Images/action_added.gif")" alt="@Resources.Repository_Commit_Added" /></text>
                        }
                        else if (item.Type == GitSharp.ChangeType.Modified)
                        {
                            <text><img src="@Url.Content("~/Content/Images/action_modified.gif")" alt="@Resources.Repository_Commit_Modified" /></text>
                        }
                        else if (item.Type == GitSharp.ChangeType.Deleted)
                        {
                            <text><img src="@Url.Content("~/Content/Images/action_deleted.gif")" alt="@Resources.Repository_Commit_Deleted" /></text>
                        }
                        else if (item.Type == GitSharp.ChangeType.Renamed)
                        {
                            <text><img src="@Url.Content("~/Content/Images/action_renamed.gif")" alt="@Resources.Repository_Commit_Renamed" /></text>
                        }
                        else if (item.Type == GitSharp.ChangeType.Copied)
                        {
                            <text><img src="@Url.Content("~/Content/Images/action_copied.gif")" alt="@Resources.Repository_Commit_Copied" /></text>
                        }
                        else if (item.Type == GitSharp.ChangeType.TypeChanged)
                        {
                            <text><img src="@Url.Content("~/Content/Images/action_typechanged.gif")" alt="@Resources.Repository_Commit_TypeChanged" /></text>
                        }
                        @if (item.Type != GitSharp.ChangeType.Deleted)
                        {
                            @Html.ActionLink(item.Path, "Tree", new { id = ViewBag.ID, path = item.Path, name = Model.ID })
                        }
                        else
                        {
                            @item.Path
                        }
                    </p>
                </div>
            }
        </div>
    </div>
}

Bonobo.Git.Server/Bonobo.Git.Server/Views/Repository/Create.cshtml
@using Bonobo.Git.Server.Extensions
@model Bonobo.Git.Server.Models.RepositoryDetailModel
@{
    ViewBag.Title = Resources.Repository_Create_Title;
}
<h2>@Resources.Repository_Create_Title</h2>
@using (Html.BeginForm("Create", "Repository", FormMethod.Post, new { @class = "uniForm" }))
{    
    @Html.ValidationSummary(false, Resources.Repository_Create_Fail, new { @id = "errorMsg" })
    <fieldset>
        <h3>@Resources.Repository_Create_Informations</h3>
        <div class="ctrlHolder">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @class = "textInput small" })<em>*</em>
            <p class="formHint">@Html.ValidationMessageFor(m => m.Name)</p>
        </div>
        <div class="ctrlHolder">
            @Html.LabelFor(m => m.Description)
            @Html.TextAreaFor(m => m.Description, new { @class = "textInput medium" })
            <p class="formHint"></p>
        </div>
        <div class="ctrlHolder noLabel">
            @Html.LabelFor(m => m.AllowAnonymous)
            @Html.CheckBoxFor(m => m.AllowAnonymous)
            <p class="formHint">
                @Resources.Repository_AllowAnonymousHint
            </p>
        </div>
        <div class="ctrlHolder">
            @Html.LabelFor(m => m.Users)
            @Html.ListBoxFor(m => m.Users, new MultiSelectList(ViewData["AvailableUsers"] as System.Collections.IEnumerable), new { @class = "selectInput medium" })
            <p class="formHint">
                @Resources.Repository_UsersHint
            </p>
        </div>
        <div class="ctrlHolder">
            @Html.LabelFor(m => m.Administrators)
            @Html.ListBoxFor(m => m.Administrators, new MultiSelectList(ViewData["AvailableAdministrators"] as System.Collections.IEnumerable), new { @class = "selectInput medium" })
            <p class="formHint">
                @Html.ValidationMessageFor(m => m.Administrators)
                @Resources.Repository_AdministratorsHint
            </p>
        </div>
        <div class="ctrlHolder">
            @Html.LabelFor(m => m.Teams)
            @Html.ListBoxFor(m => m.Teams, new MultiSelectList(ViewData["AvailableTeams"] as System.Collections.IEnumerable), new { @class = "selectInput medium" })
            <p class="formHint">
                @Resources.Repository_TeamsHint                
            </p>
        </div>
        <div class="buttonHolder">
            @Html.ActionLink("← " + Resources.Repository_Create_Back, "Index", null, new { @class = "secondaryAction" })
            <button type="reset" class="secondaryAction">← @Resources.Reset</button>
            <input type="submit" value="@Resources.Repository_Create_Submit" class="primaryAction" />
        </div>
    </fieldset>
}

Bonobo.Git.Server/Bonobo.Git.Server/Views/Repository/Delete.cshtml
@model Bonobo.Git.Server.Models.RepositoryDetailModel
@{
    ViewBag.Title = Resources.Delete_Title;
}
@using (Html.BeginForm("Delete", "Repository", FormMethod.Post, new { @class = "uniForm" }))
{
    <fieldset class="deleteForm">
        <h3>@String.Format(Resources.Delete_ConfirmationText, Model.Name)</h3>
        @Html.HiddenFor(m => m.Name)
        <div class="buttonHolder"> 
            @Html.ActionLink("← " + Resources.Delete_Back, "Index", null, new { @class = "secondaryAction" })
            <input type="submit" value="@Resources.Delete_Confirm" class="primaryAction" />
       </div>
    </fieldset> 
}

Bonobo.Git.Server/Bonobo.Git.Server/Views/Repository/Detail.cshtml
@model Bonobo.Git.Server.Models.RepositoryDetailModel
@{
    Layout = "~/Views/Repository/_RepositoryLayout.cshtml";
    ViewBag.Title = Resources.Repository_Detail_Title;
    var serverAddress = Request.Url.ToString().Substring(0, Request.Url.ToString().IndexOf("Repository"));
}
@if (Model != null)
{   
    <div class="uniForm">
        <fieldset class="inlineLabels detail">
            <h3>@Model.Name</h3>
            <div class="ctrlHolder">
                <h5>@Html.LabelFor(m => m.Name)</h5>
                <div class="content">@Model.Name</div>
            </div>
            <div class="ctrlHolder">
                <h5>
                    <label>@Resources.Repository_Detail_Location</label></h5>
                <div class="content">
                    @String.Concat(serverAddress, MvcApplication.GitRepositoryPrefix, Model.Name)
                    @if (Model.AllowAnonymous)
                    {
                        <br />@String.Concat(serverAddress, MvcApplication.AnonymousGitRepositoryPrefix, Model.Name)
                    }
                </div>
            </div>
            <div class="ctrlHolder">
                <h5>@Html.LabelFor(m => m.Description)</h5>
                <div class="content">@Model.Description</div>
            </div>
            <div class="ctrlHolder">
                <h5>@Html.LabelFor(m => m.AllowAnonymous)</h5>
                <div class="content">
                    @if (Model.AllowAnonymous)
                    {
                        @Resources.Repository_Detail_Yes
                    }
                    else
                    {
                        @Resources.Repository_Detail_No
                    }
                </div>
            </div>
            <div class="ctrlHolder">
                <h5>@Html.LabelFor(m => m.Users)</h5>
                <div class="content">
                    @for (int i = 0; i < Model.Users.Length; i++)
                    {
                        @Html.ActionLink(@Model.Users[i], "Detail", "Account", new { id = @Model.Users[i] }, null)if (i + 1 != Model.Users.Length)
                                                                                                                  {<text>, </text>}
                    }
                </div>
            </div>
            <div class="ctrlHolder">
                <h5>@Html.LabelFor(m => m.Administrators)</h5>
                <div class="content">
                    @for (int i = 0; i < Model.Administrators.Length; i++)
                    {
                        @Html.ActionLink(@Model.Administrators[i], "Detail", "Account", new { id = @Model.Administrators[i] }, null)if (i + 1 != Model.Administrators.Length)
                                                                                                                                    {<text>, </text>}
                    }
                </div>
            </div>
            <div class="ctrlHolder">
                <h5>@Html.LabelFor(m => m.Teams)</h5>
                <div class="content">
                    @for (int i = 0; i < Model.Teams.Length; i++)
                    {
                        @Html.ActionLink(@Model.Teams[i], "Detail", "Team", new { id = @Model.Teams[i] }, null)if (i + 1 != Model.Teams.Length)
                                                                                                               {<text>, </text>}
                    }
                </div>
            </div>
            <div class="buttonHolder">
                @Html.ActionLink("←  " + Resources.Repository_Detail_Back, "Index", null, new { @class = "secondaryAction" })
                @if (Model.IsCurrentUserAdministrator)
                {
                    @Html.ActionLink(Resources.Repository_Detail_Edit, "Edit", new { id = Model.Name }, new { @class = "primaryAction" })@Html.ActionLink(Resources.Repository_Detail_Delete, "Delete", new { id = Model.Name }, new { @class = "primaryAction deleteButton" })
                }
            </div>
        </fieldset>
    </div>
}

Bonobo.Git.Server/Bonobo.Git.Server/Views/Repository/Edit.cshtml
@using Bonobo.Git.Server.Extensions
@model Bonobo.Git.Server.Models.RepositoryDetailModel
@{
    ViewBag.Title = Resources.Repository_Edit_Title;
}
@if (Model == null)
{   
    @Html.Partial("~/Views/Shared/_ItemNotFound.cshtml") 
}
else
{
    <text>
    <h2>@Resources.Repository_Edit_Title</h2>
    @using (Html.BeginForm("Edit", "Repository", FormMethod.Post, new { @class = "uniForm" }))
    {
        if (ViewBag.UpdateSuccess != null && ViewBag.UpdateSuccess)
        {
        <div id="okMsg">
            <p>@Resources.Repository_Edit_UpdateSuccess</p>
        </div>
        }
        @Html.ValidationSummary(false, Resources.Repository_Edit_Fail, new { @id = "errorMsg" })
        @Html.HiddenFor(m => m.Name);
        <fieldset>
            <h3>@Model.Name</h3>
            <div class="ctrlHolder">
                @Html.LabelFor(m => m.Description)
                @Html.TextAreaFor(m => m.Description, new { @class = "textInput medium" })
                <p class="formHint"></p>
            </div>
            <div class="ctrlHolder noLabel">
                @Html.LabelFor(m => m.AllowAnonymous)
                @Html.CheckBoxFor(m => m.AllowAnonymous)
                <p class="formHint">
                    @Resources.Repository_AllowAnonymousHint
                </p>
            </div>
            <div class="ctrlHolder">
                @Html.LabelFor(m => m.Users)
                @Html.ListBoxFor(m => m.Users, new MultiSelectList(ViewData["AvailableUsers"] as System.Collections.IEnumerable), new { @class = "selectInput medium" })
                <p class="formHint">
                    @Resources.Repository_UsersHint
                </p>
            </div>
            <div class="ctrlHolder">
                @Html.LabelFor(m => m.Administrators)
                @Html.ListBoxFor(m => m.Administrators, new MultiSelectList(ViewData["AvailableAdministrators"] as System.Collections.IEnumerable), new { @class = "selectInput medium" })
                <p class="formHint">
                    @Html.ValidationMessageFor(m => m.Administrators)
                    @Resources.Repository_AdministratorsHint
                </p>
            </div>
            <div class="ctrlHolder">
                @Html.LabelFor(m => m.Teams)
                @Html.ListBoxFor(m => m.Teams, new MultiSelectList(ViewData["AvailableTeams"] as System.Collections.IEnumerable), new { @class = "selectInput medium" })
                <p class="formHint">
                    @Resources.Repository_TeamsHint     
                </p>
            </div>
            <div class="buttonHolder">
                @Html.ActionLink("← " + Resources.Repository_Edit_Back, "Index", null, new { @class = "secondaryAction" })
                <button type="reset" class="secondaryAction">← @Resources.Reset</button>
                <input type="submit" value="@Resources.Repository_Edit_Submit" class="primaryAction" />
            </div>
        </fieldset>
    }
    </text>
}

Bonobo.Git.Server/Bonobo.Git.Server/Views/Repository/Tree.cshtml
@using Bonobo.Git.Server.Extensions
@model RepositoryTreeModel
@{
    Layout = "~/Views/Repository/_RepositoryLayout.cshtml";
    ViewBag.Title = Resources.Repository_Tree_Title;
}
@if (Model != null)
{
    <div class="uniForm">
        <fieldset class="inlineLabels detail">
            <h3>@Model.Name</h3>
        </fieldset>
    </div>
    <div class="repositoryContent">
        @Html.Partial("_BranchSwitcher")
        @Html.Partial("_AddressBar")
        @if (!Model.IsTree)
        {
            <div class="controlPanel">
                <p>@Html.ActionLink(@Resources.Repository_Tree_Download, "Tree", new { name = Model.File.Tree, path = Model.File.Path + ".download" }, new { @class = "downloadLink" })</p>
            </div>
        }
        @if (Model.IsTree)
        {
            var grid = new WebGrid(source: Model.Files, rowsPerPage: 15);
            <div class="w-grid">
                @grid.GetHtml(
                    tableStyle: "grid",
                    headerStyle: "head",
                    alternatingRowStyle: "even",
                    columns: grid.Columns(
                     grid.Column("Name", header: typeof(RepositoryTreeDetailModel).GetDisplayValue("Name"), format: (item) => @Html.ActionLink((string)item.Name, "Tree", new { name = item.Tree, path = item.Path + ".browse" }, new { @class = item.IsTree ? "directory" : item.IsImage ? "image" : "file" })),
                        grid.Column("CommitMessage", header: typeof(RepositoryTreeDetailModel).GetDisplayValue("CommitMessage")),
                        grid.Column("CommitDate", header: typeof(RepositoryTreeDetailModel).GetDisplayValue("CommitDate"), format: item => ((DateTime)item.CommitDate).ToString(Resources.DateTimeFormat)),
                        grid.Column("Author", header: typeof(RepositoryTreeDetailModel).GetDisplayValue("Author"))
                    )
                )
            </div>
        }
        else if (Model.IsImage)
        {
            <img class="fileImage" alt="@Model.File.Name" src="@Url.Action("Show", "Image", new { repository = ViewBag.ID, tree = Model.File.Tree, path = Model.File.Path })" />
        }
        else if (Model.IsTextFile)
        {
            <pre class="brush: @Model.TextBrush;">@Model.Text</pre>   
        }
    </div>
}