Bonobo.Git.Server/Bonobo.Git.Server/Controllers/RepositoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Bonobo.Git.Server.Data;
using Bonobo.Git.Server.Security;
using Bonobo.Git.Server.Models;
using Bonobo.Git.Server.App_GlobalResources;
using System.IO;
using System.Configuration;
using System.Text.RegularExpressions;

namespace Bonobo.Git.Server.Controllers
{
    public class RepositoryController : Controller
    {
        [Dependency]
        public ITeamRepository TeamRepository { get; set; }

        [Dependency]
        public IRepositoryRepository RepositoryRepository { get; set; }

        [Dependency]
        public IMembershipService MembershipService { get; set; }

        [Dependency]
        public IRepositoryPermissionService RepositoryPermissionService { get; set; }

        [FormsAuthorizeAttribute]
        public ActionResult Index()
        {
            return View(GetIndexModel());
        }

        [FormsAuthorizeRepository(RequiresRepositoryAdministrator = true)]
        public ActionResult Edit(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var model = ConvertRepositoryModel(RepositoryRepository.GetRepository(id));
                PopulateEditData();
                return View(model);
            }
            return View();
        }

        [HttpPost]
        [FormsAuthorizeRepository(RequiresRepositoryAdministrator = true)]
        public ActionResult Edit(RepositoryDetailModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Administrators.Contains(User.Identity.Name))
                {
                    RepositoryRepository.Update(ConvertRepositoryDetailModel(model));
                    ViewBag.UpdateSuccess = true;
                }
                else
                {
                    ModelState.AddModelError("Administrators", Resources.Repository_Edit_CantRemoveYourself);
                }
            }
            PopulateEditData();
            return View(model);
        }

        [FormsAuthorizeAttribute]
        public ActionResult Create()
        {
            if (!User.IsInRole(Definitions.Roles.Administrator) && !UserConfigurationManager.AllowUserRepositoryCreation)
            {
                return RedirectToAction("Unauthorized", "Home");
            }

            var model = new RepositoryDetailModel
            {
                Administrators = new string[] { User.Identity.Name },
            };
            PopulateEditData();
            return View(model);
        }

        [HttpPost]
        [FormsAuthorizeAttribute]
        public ActionResult Create(RepositoryDetailModel model)
        {
            if (!User.IsInRole(Definitions.Roles.Administrator) && !UserConfigurationManager.AllowUserRepositoryCreation)
            {
                return RedirectToAction("Unauthorized", "Home");
            }

            if (model != null && !String.IsNullOrEmpty(model.Name))
            {
                model.Name = Regex.Replace(model.Name, @"\s", "");
            }

            if (String.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("Name", Resources.Repository_Create_NameFailure);
            }
            else if (ModelState.IsValid)
            {
                if (RepositoryRepository.Create(ConvertRepositoryDetailModel(model)))
                {
                    string path = Path.Combine(UserConfigurationManager.Repositories, model.Name);
                    if (!Directory.Exists(path))
                    {
                        using (var repository = new GitSharp.Core.Repository(new DirectoryInfo(path)))
                        {
                            repository.Create(true);
                        }
                        TempData["CreateSuccess"] = true;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        RepositoryRepository.Delete(model.Name);
                        ModelState.AddModelError("", Resources.Repository_Create_DirectoryExists);
                    }
                }
                else
                {
                    ModelState.AddModelError("", Resources.Repository_Create_Failure);
                }
            }
            PopulateEditData();
            return View(model);
        }

        [FormsAuthorizeRepository(RequiresRepositoryAdministrator = true)]
        public ActionResult Delete(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                return View(new RepositoryDetailModel { Name = id });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [FormsAuthorizeRepository(RequiresRepositoryAdministrator = true)]
        public ActionResult Delete(RepositoryDetailModel model)
        {
            if (model != null && !String.IsNullOrEmpty(model.Name))
            {
                string path = Path.Combine(UserConfigurationManager.Repositories, model.Name);
                if (Directory.Exists(path))
                {
                    DeleteFileSystemInfo(new DirectoryInfo(path));
                }
                RepositoryRepository.Delete(model.Name);
                TempData["DeleteSuccess"] = true;
            }
            return RedirectToAction("Index");
        }

        [FormsAuthorizeRepository]
        public ActionResult Detail(string id)
        {
            ViewBag.ID = id;
            if (!String.IsNullOrEmpty(id))
            {
                var model = ConvertRepositoryModel(RepositoryRepository.GetRepository(id));
                if (model != null)
                {
                    model.IsCurrentUserAdministrator = RepositoryPermissionService.IsRepositoryAdministrator(User.Identity.Name, id);
                }
                return View(model);
            }
            return View();
        }

        [FormsAuthorizeRepository]
        public ActionResult Tree(string id, string name, string path)
        {
            ViewBag.ID = id;
            if (!String.IsNullOrEmpty(id))
            {
                bool download = false;
                if (path != null)
                {
                    if (path.EndsWith(".browse"))
                    {
                        path = path.Substring(0, path.Length - 7);
                    }
                    else if (path.EndsWith(".download"))
                    {
                        path = path.Substring(0, path.Length - 9);
                        download = true;
                    }
                }
                path = path != null ? path.Replace(".browse", "") : null;
                using (var browser = new RepositoryBrowser(Path.Combine(UserConfigurationManager.Repositories, id)))
                {
                    string branchName;
                    var files = browser.Browse(name, path, out branchName);
                    PopulateBranchesData(browser, branchName);
                    PopulateAddressBarData(name, path);
                    return DisplayFiles(files, path, id, download);
                }
            }
            return View();
        }

        [FormsAuthorizeRepository]
        public ActionResult Commits(string id, string name)
        {
            ViewBag.ID = id;
            if (!String.IsNullOrEmpty(id))
            {
                using (var browser = new RepositoryBrowser(Path.Combine(UserConfigurationManager.Repositories, id)))
                {
                    string currentBranchName;
                    var commits = browser.GetCommits(name, out currentBranchName);
                    PopulateBranchesData(browser, currentBranchName);
                    return View(new RepositoryCommitsModel { Commits = commits, Name = id });
                }
            }

            return View();
        }

        [FormsAuthorizeRepository]
        public ActionResult Commit(string id, string commit)
        {
            ViewBag.ID = id;
            if (!String.IsNullOrEmpty(id))
            {
                using (var browser = new RepositoryBrowser(Path.Combine(UserConfigurationManager.Repositories, id)))
                {
                    var model = browser.GetCommitDetail(commit);
                    model.Name = id;
                    return View(model);
                }
            }

            return View();
        }

        private ActionResult DisplayFiles(IEnumerable<RepositoryTreeDetailModel> files, string path, string id, bool returnAsBinary)
        {
            if (files != null)
            {
                var model = new RepositoryTreeModel();
                model.Name = id;
                model.IsTree = !(files.Count() == 1 && !files.First().IsTree && files.First().Path == path);
                if (model.IsTree)
                {
                    model.Files = files.OrderByDescending(i => i.IsTree).ThenBy(i => i.Name);
                }
                else
                {
                    model.File = files.First();
                    if (!returnAsBinary)
                    {
                        model.Text = FileDisplayHandler.GetText(model.File.Data);
                        model.IsTextFile = model.Text != null;

                        if (model.IsTextFile)
                        {
                            model.TextBrush = FileDisplayHandler.GetBrush(model.File.Name);
                        }

                        if (!model.IsTextFile)
                        {
                            model.IsImage = FileDisplayHandler.IsImage(model.File.Name);
                        }
                    }

                    if (!model.IsImage && !model.IsTextFile)
                    {
                        using (var stream = new MemoryStream(model.File.Data))
                        {

Bonobo.Git.Server/Bonobo.Git.Server/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bonobo.Git.Server.Models;
using System.Configuration;
using System.Web.Configuration;
using System.IO;
using Bonobo.Git.Server.App_GlobalResources;

namespace Bonobo.Git.Server.Controllers
{
    public class SettingsController : Controller
    {
        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Index()
        {            
            return View(new GlobalSettingsModel
            {              
                AllowAnonymousPush = UserConfigurationManager.AllowAnonymousPush,
                RepositoryPath = UserConfigurationManager.Repositories,
                AllowAnonymousRegistration = UserConfigurationManager.AllowAnonymousRegistration,
                AllowUserRepositoryCreation = UserConfigurationManager.AllowUserRepositoryCreation,
            });
        }

        [HttpPost]
        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Index(GlobalSettingsModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Directory.Exists(model.RepositoryPath))
                    {
                        System.Security.AccessControl.DirectorySecurity ds = Directory.GetAccessControl(model.RepositoryPath);

                        UserConfigurationManager.AllowAnonymousPush = model.AllowAnonymousPush;
                        UserConfigurationManager.Repositories = model.RepositoryPath;
                        UserConfigurationManager.AllowAnonymousRegistration = model.AllowAnonymousRegistration;
                        UserConfigurationManager.AllowUserRepositoryCreation = model.AllowUserRepositoryCreation;
                        UserConfigurationManager.Save();

                        ViewBag.UpdateSuccess = true;
                    }
                    else
                    {
                        ModelState.AddModelError("RepositoryPath", Resources.Settings_RepositoryPathNotExists);
                    }
                }
                catch (UnauthorizedAccessException)
                {
                    ModelState.AddModelError("RepositoryPath", Resources.Settings_RepositoryPathNotExists);
                }
            }

            return View(model);
        }
    }
}

Bonobo.Git.Server/Bonobo.Git.Server/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Bonobo.Git.Server.Data;
using Bonobo.Git.Server.Models;
using Bonobo.Git.Server.Security;
using Bonobo.Git.Server.App_GlobalResources;

namespace Bonobo.Git.Server.Controllers
{
    public class TeamController : Controller
    {
        [Dependency]
        public ITeamRepository TeamRepository { get; set; }

        [Dependency]
        public IMembershipService MembershipService { get; set; }

        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Index()
        {
            return View(ConvertTeamModels(TeamRepository.GetAllTeams()));
        }

        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Edit(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var model = ConvertTeamModel(TeamRepository.GetTeam(id));
                PopulateViewData();
                return View(model);
            }
            return View();
        }

        [HttpPost]
        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Edit(TeamDetailModel model)
        {           
            if (ModelState.IsValid)
            {
                TeamRepository.Update(ConvertTeamDetailModel(model));
                ViewBag.UpdateSuccess = true;
            }
            PopulateViewData();
            return View(model);
        }

        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Create()
        {
            var model = new TeamDetailModel { };
            PopulateViewData();
            return View(model);
        }

        [HttpPost]
        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Create(TeamDetailModel model)
        {
            while (!String.IsNullOrEmpty(model.Name) && model.Name.Last() == ' ')
            {
                model.Name = model.Name.Substring(0, model.Name.Length - 1);
            }

            if (ModelState.IsValid)
            {
                if (TeamRepository.Create(ConvertTeamDetailModel(model)))
                {
                    TempData["CreateSuccess"] = true;
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", Resources.Team_Create_Failure);
                }
            }

            PopulateViewData();
            return View(model);
        }

        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Delete(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                return View(new TeamDetailModel { Name = id });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [FormsAuthorizeAttribute(Roles = Definitions.Roles.Administrator)]
        public ActionResult Delete(TeamDetailModel model)
        {
            if (model != null && !String.IsNullOrEmpty(model.Name))
            {
                TeamRepository.Delete(model.Name);
                TempData["DeleteSuccess"] = true;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [FormsAuthorizeAttribute]
        public ActionResult Detail(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                return View(ConvertTeamModel(TeamRepository.GetTeam(id)));
            }
            return View();
        }

        private IEnumerable<TeamDetailModel> ConvertTeamModels(IEnumerable<TeamModel> models)
        {
            var result = new List<TeamDetailModel>();
            foreach (var item in models)
            {
                result.Add(ConvertTeamModel(item));
            }
            return result;
        }

        private TeamDetailModel ConvertTeamModel(TeamModel model)
        {
            return model == null ? null : new TeamDetailModel
            {
                Name = model.Name,
                Description = model.Description,
                Members = model.Members,
                Repositories = model.Repositories,
            };
        }

        private TeamModel ConvertTeamDetailModel(TeamDetailModel model)
        {
            return new TeamModel
            {
                Name = model.Name,
                Description = model.Description,
                Members = model.Members,
                Repositories = model.Repositories,
            };
        }

        private void PopulateViewData()
        {
            ViewData["AvailableUsers"] = MembershipService.GetAllUsers().Select(i => i.Username).ToArray();
        }
    }
}

Bonobo.Git.Server/Bonobo.Git.Server/Views/Shared/_ItemNotFound.cshtml
<h2 class="error">@Resources.Item_NotFound</h2>

Bonobo.Git.Server/Bonobo.Git.Server/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="en" />
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/uni/css/uni-form.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/uni/css/default.uni-form.css")" rel="stylesheet" type="text/css" />
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Content/syntaxhighlighter/styles/shCoreDefault.css")"/>
    <!--[if lte IE 7]><link rel="stylesheet" href="@Url.Content("~/Content/Msie.css")" type="text/css" media="screen,projection" /><![endif]-->
</head>
<body>
    <div class="page" id="@ViewContext.ViewData["PageID"]">
        <div id="header">
            <div id="title">
                <h1>@Html.ActionLink(Resources.Layout_Title, "", "")</h1>
            </div>
            <div id="topMenu">
                <div id="accountInfo">
                    @if (Request.IsAuthenticated)
                    {
                        <p><strong>@Context.User.Identity.Name</strong> [ @Html.ActionLink(Resources.Layout_AccountSettings, "Edit", "Account", new { id = User.Identity.Name }, null) | @Html.ActionLink(Resources.Layout_LogOff, "LogOff", "Home") ]</p>
                    }
                    else
                    {
                        if (UserConfigurationManager.AllowAnonymousRegistration)
                        {
                            <p>[ @Html.ActionLink(Resources.Layout_LogOn, "LogOn", "Home") | @Html.ActionLink(Resources.Layout_Register, "Create", "Account")]</p>
                        }
                        else
                        {
                            <p>[ @Html.ActionLink(Resources.Layout_LogOn, "LogOn", "Home") ]</p>
                        }
                    }
                </div>
                <div id="languageBar">
                    <p>@Html.ActionLink("Čeština", "ChangeCulture", "Home", new { lang = "cs-CZ", returnUrl = this.Request.RawUrl }, null)  @Html.ActionLink("Japanse", "ChangeCulture", "Home", new { lang = "ja-JP", returnUrl = this.Request.RawUrl }, new { @id = "jp" }) @Html.ActionLink("Chinese", "ChangeCulture", "Home", new { lang = "zh-CN", returnUrl = this.Request.RawUrl }, new { @id = "zh" }) @Html.ActionLink("English", "ChangeCulture", "Home", new { lang = "en", returnUrl = this.Request.RawUrl }, new { @id = "en" })</p>
                </div>
            </div>
        </div>
        <div class="window">
            <div id="main">
                <div class="clearfix">
                    <div id="menu">
                        @if (Request.IsAuthenticated)
                        {
                            <ul>
                                <li>@Html.ActionLink(Resources.Layout_Repositories, "Index", "Repository")</li>
                                <li>@Html.ActionLink(Resources.Layout_About, "About", "Home")</li>
                            </ul>                
                        }
                        @if (User.IsInRole(Definitions.Roles.Administrator))
                        {
                            <h3>@Resources.Layout_Administration</h3>
                            <ul>
                                <li>@Html.ActionLink(Resources.Layout_AdministrationUsers, "Index", "Account")</li>
                                <li>@Html.ActionLink(Resources.Layout_AdministrationTeams, "Index", "Team")</li>
                                <li>@Html.ActionLink(Resources.Layout_AdministrationGlobalSettings, "Index", "Settings")</li>
                            </ul>
                        }
                    </div>
                    <div id="content">                        
                        @RenderBody()
                    </div>
                </div>
                <div id="footer">
                    <p>&copy; 2011 <a href="http://www.chodounsky.net">Jakub Chodounský</a>. @Resources.Layout_Footer_Copyright</p>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shCore.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushJScript.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushBash.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushCpp.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushCsharp.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushCss.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushDelphi.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushDiff.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushErlang.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushJava.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushPerl.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushPhp.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushPowerShell.js")"></script>    
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushPython.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushRuby.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushScala.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushSql.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushVb.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushXml.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/syntaxhighlighter/scripts/shBrushPlain.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/uni/js/uni-form-validation.jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/MicrosoftAjax.js")" type="text/javascript"></script>   
    <script type="text/javascript">
        SyntaxHighlighter.all();
        $('form.uniForm').uniform();
    </script>
</body>
</html>